/**
 * Schema Merger
 * Merges prisma/_base.prisma + all src/modules/*\/schema.prisma files
 * into a single prisma/schema.prisma (the Prisma "source of truth").
 *
 * Used by:
 *  - scripts/merge-schemas.ts  (CLI: npm run db:merge)
 *  - module-manager install-handler (auto-migrate on module install)
 */

import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(process.cwd());
const BASE_SCHEMA_PATH = path.join(ROOT, 'prisma', '_base.prisma');
const OUTPUT_SCHEMA_PATH = path.join(ROOT, 'prisma', 'schema.prisma');
const MODULES_DIR = path.join(ROOT, 'src', 'modules');

export interface MergeResult {
  mergedCount: number;
  moduleSchemas: string[];
  outputPath: string;
}

/**
 * Merge all module schemas into prisma/schema.prisma
 * @param extraSchemaPaths - Optional additional schema file paths to include
 *                           (e.g. a freshly extracted module not yet in MODULES_DIR)
 */
export function mergeSchemas(extraSchemaPaths: string[] = []): MergeResult {
  if (!fs.existsSync(BASE_SCHEMA_PATH)) {
    throw new Error(`Base schema not found: ${BASE_SCHEMA_PATH}`);
  }

  const baseContent = fs.readFileSync(BASE_SCHEMA_PATH, 'utf-8');

  // Discover module schemas
  const moduleSchemas: string[] = [];
  const parts: string[] = [];

  if (fs.existsSync(MODULES_DIR)) {
    const moduleDirs = fs.readdirSync(MODULES_DIR, { withFileTypes: true })
      .filter(d => d.isDirectory())
      .map(d => d.name)
      .sort(); // deterministic merge order

    for (const moduleId of moduleDirs) {
      const schemaPath = path.join(MODULES_DIR, moduleId, 'schema.prisma');
      if (fs.existsSync(schemaPath)) {
        const content = fs.readFileSync(schemaPath, 'utf-8').trim();
        if (content) {
          parts.push(
            `// ══════════════════════════════════════════════\n` +
            `// Module: ${moduleId}\n` +
            `// Source: src/modules/${moduleId}/schema.prisma\n` +
            `// ══════════════════════════════════════════════\n` +
            content
          );
          moduleSchemas.push(`src/modules/${moduleId}/schema.prisma`);
        }
      }
    }
  }

  // Include extra schema paths (for newly extracted modules)
  for (const extraPath of extraSchemaPaths) {
    if (fs.existsSync(extraPath)) {
      const content = fs.readFileSync(extraPath, 'utf-8').trim();
      if (content) {
        parts.push(
          `// ══════════════════════════════════════════════\n` +
          `// Extra schema: ${path.basename(path.dirname(extraPath))}\n` +
          `// ══════════════════════════════════════════════\n` +
          content
        );
        moduleSchemas.push(extraPath);
      }
    }
  }

  const header =
    `// ================================================================\n` +
    `// AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY\n` +
    `// Generated by: scripts/merge-schemas.ts\n` +
    `// Last merged: ${new Date().toISOString()}\n` +
    `//\n` +
    `// To make changes:\n` +
    `//   Base schema  → prisma/_base.prisma\n` +
    `//   Module model → src/modules/<module>/schema.prisma\n` +
    `//   Then run: npm run db:migrate\n` +
    `// ================================================================\n\n`;

  const merged = header + baseContent.trim() + '\n\n' + parts.join('\n\n');
  fs.writeFileSync(OUTPUT_SCHEMA_PATH, merged, 'utf-8');

  return {
    mergedCount: moduleSchemas.length,
    moduleSchemas,
    outputPath: OUTPUT_SCHEMA_PATH,
  };
}
