import { CanvasElement } from './types';

// Professional CR80 Card Dimensions (Standard ID-1: 85.60 × 53.98 mm -> Ratio ~1.586)
export const CANVAS_WIDTH = 380;
export const CANVAS_HEIGHT = 600;
export const HORIZONTAL_CANVAS_WIDTH = 600;
export const HORIZONTAL_CANVAS_HEIGHT = 380;

// ─── Professional Prebuilt Template Presets ──────────────────────────────────
export const TEMPLATE_MILITARY_OFFICIAL: CanvasElement[] = [
  {
    id: "bg-header",
    type: "rect",
    field: "static",
    x: 0,
    y: 0,
    width: 380,
    height: 155,
    backgroundColor: "#1e3a8a",
    gradientEnabled: true,
    gradientFrom: "#1e3a8a",
    gradientTo: "#0f172a",
    gradientDirection: "to-b",
    zIndex: 1
  },
  {
    id: "h-garuda",
    type: "emblem",
    field: "static",
    content: "garuda",
    x: 155,
    y: 12,
    width: 70,
    height: 65,
    zIndex: 3
  },
  {
    id: "title",
    type: "text",
    field: "static",
    content: "บัตรประจำตัวข้าราชการ",
    x: 0,
    y: 78,
    width: 380,
    height: 34,
    fontSize: 15,
    color: "#ffffff",
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 3
  },
  {
    id: "org",
    type: "text",
    field: "department",
    x: 0,
    y: 114,
    width: 380,
    height: 28,
    fontSize: 10.5,
    color: "#93c5fd",
    textAlign: "center",
    zIndex: 3
  },
  {
    id: "avatar",
    type: "image",
    field: "avatar",
    x: 105,
    y: 168,
    width: 170,
    height: 190,
    backgroundColor: "#e2e8f0",
    borderWidth: 3,
    borderColor: "#1e3a8a",
    borderRadius: 12,
    boxShadow: "md",
    zIndex: 4
  },
  {
    id: "name",
    type: "text",
    field: "fullName",
    x: 0,
    y: 370,
    width: 380,
    height: 40,
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 3
  },
  {
    id: "pos",
    type: "text",
    field: "position",
    x: 0,
    y: 408,
    width: 380,
    height: 30,
    fontSize: 11.5,
    color: "#475569",
    textAlign: "center",
    zIndex: 3
  },
  {
    id: "rank-pill",
    type: "ribbon",
    field: "rank",
    x: 75,
    y: 444,
    width: 230,
    height: 32,
    fontSize: 10.5,
    color: "#ffffff",
    backgroundColor: "#1e3a8a",
    dynamicBg: true,
    fontWeight: "bold",
    textAlign: "center",
    borderRadius: 20,
    zIndex: 3
  },
  {
    id: "box-info",
    type: "rect",
    field: "static",
    x: 25,
    y: 486,
    width: 330,
    height: 66,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    zIndex: 2
  },
  {
    id: "lbl-id",
    type: "text",
    field: "static",
    content: "หมายเลขประจำตัว:",
    x: 40,
    y: 498,
    width: 150,
    height: 22,
    fontSize: 9,
    color: "#64748b",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 3
  },
  {
    id: "val-id",
    type: "text",
    field: "badgeNo",
    x: 190,
    y: 498,
    width: 150,
    height: 22,
    fontSize: 10,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "right",
    zIndex: 3
  },
  {
    id: "lbl-bld",
    type: "text",
    field: "static",
    content: "หมู่โลหิต (Blood):",
    x: 40,
    y: 522,
    width: 150,
    height: 22,
    fontSize: 9,
    color: "#64748b",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 3
  },
  {
    id: "val-bld",
    type: "text",
    field: "bloodType",
    x: 190,
    y: 522,
    width: 150,
    height: 22,
    fontSize: 10,
    color: "#dc2626",
    fontWeight: "bold",
    textAlign: "right",
    zIndex: 3
  },
  {
    id: "bg-foot",
    type: "rect",
    field: "static",
    x: 0,
    y: 565,
    width: 380,
    height: 35,
    backgroundColor: "#1e3a8a",
    zIndex: 1
  },
  {
    id: "foot-txt",
    type: "text",
    field: "static",
    content: "หากพบเห็นกรุณาส่งคืนหน่วยงานต้นสังกัด",
    x: 0,
    y: 572,
    width: 380,
    height: 22,
    fontSize: 8,
    color: "#bfdbfe",
    textAlign: "center",
    zIndex: 3
  }
];

export const TEMPLATE_MODERN_TECH: CanvasElement[] = [
  {
    id: "bg-card",
    type: "rect",
    field: "static",
    x: 0,
    y: 0,
    width: 380,
    height: 600,
    backgroundColor: "#ffffff",
    zIndex: 0
  },
  {
    id: "hdr-band",
    type: "rect",
    field: "static",
    x: 0,
    y: 0,
    width: 380,
    height: 225,
    backgroundColor: "#4f46e5",
    gradientEnabled: true,
    gradientFrom: "#4f46e5",
    gradientTo: "#7c3aed",
    gradientDirection: "to-br",
    dynamicBg: true,
    zIndex: 1
  },
  {
    id: "hdr-title",
    type: "text",
    field: "static",
    content: "DIGITAL IDENTIFICATION",
    x: 0,
    y: 18,
    width: 380,
    height: 28,
    fontSize: 10,
    color: "#ffffff",
    fontWeight: "bold",
    letterSpacing: 2,
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "avatar",
    type: "image",
    field: "avatar",
    x: 100,
    y: 72,
    width: 180,
    height: 180,
    backgroundColor: "#e2e8f0",
    borderWidth: 4,
    borderColor: "#ffffff",
    borderRadius: 100,
    boxShadow: "lg",
    dynamicBorder: true,
    zIndex: 4
  },
  {
    id: "name",
    type: "text",
    field: "fullName",
    x: 0,
    y: 268,
    width: 380,
    height: 42,
    fontSize: 17,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "pos",
    type: "text",
    field: "position",
    x: 0,
    y: 310,
    width: 380,
    height: 28,
    fontSize: 11,
    color: "#64748b",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "div-line",
    type: "line",
    field: "static",
    x: 50,
    y: 346,
    width: 280,
    height: 2,
    backgroundColor: "#e2e8f0",
    zIndex: 1
  },
  {
    id: "dept",
    type: "text",
    field: "department",
    x: 0,
    y: 358,
    width: 380,
    height: 28,
    fontSize: 10.5,
    color: "#4f46e5",
    dynamicText: true,
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "qr-code",
    type: "qr",
    field: "badgeNo",
    x: 45,
    y: 405,
    width: 110,
    height: 110,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    zIndex: 3
  },
  {
    id: "lbl-id",
    type: "text",
    field: "static",
    content: "ID NUMBER",
    x: 175,
    y: 412,
    width: 165,
    height: 22,
    fontSize: 9,
    color: "#94a3b8",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "val-id",
    type: "text",
    field: "badgeNo",
    x: 175,
    y: 434,
    width: 165,
    height: 30,
    fontSize: 12,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "lbl-rank",
    type: "text",
    field: "static",
    content: "RANK / TYPE",
    x: 175,
    y: 468,
    width: 165,
    height: 22,
    fontSize: 9,
    color: "#94a3b8",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "val-rank",
    type: "text",
    field: "rank",
    x: 175,
    y: 490,
    width: 165,
    height: 26,
    fontSize: 10.5,
    color: "#4f46e5",
    dynamicText: true,
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "holo-bar",
    type: "hologram",
    field: "static",
    x: 0,
    y: 545,
    width: 380,
    height: 24,
    zIndex: 3
  },
  {
    id: "btm-txt",
    type: "text",
    field: "static",
    content: "SECURE AUTHENTICATED SMART BADGE",
    x: 0,
    y: 574,
    width: 380,
    height: 20,
    fontSize: 7.5,
    color: "#94a3b8",
    textAlign: "center",
    zIndex: 2
  }
];

export const TEMPLATE_LANDSCAPE_EXECUTIVE: CanvasElement[] = [
  {
    id: "ls-bg",
    type: "rect",
    field: "static",
    x: 0,
    y: 0,
    width: 600,
    height: 380,
    backgroundColor: "#ffffff",
    zIndex: 0
  },
  {
    id: "ls-bar-l",
    type: "rect",
    field: "static",
    x: 0,
    y: 0,
    width: 200,
    height: 380,
    backgroundColor: "#0f172a",
    gradientEnabled: true,
    gradientFrom: "#0f172a",
    gradientTo: "#1e293b",
    gradientDirection: "to-b",
    zIndex: 1
  },
  {
    id: "ls-avatar",
    type: "image",
    field: "avatar",
    x: 25,
    y: 55,
    width: 150,
    height: 165,
    backgroundColor: "#e2e8f0",
    borderWidth: 2,
    borderColor: "#ffffff",
    borderRadius: 10,
    boxShadow: "md",
    zIndex: 3
  },
  {
    id: "ls-badge-no",
    type: "text",
    field: "badgeNo",
    x: 10,
    y: 235,
    width: 180,
    height: 22,
    fontSize: 11,
    color: "#94a3b8",
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "ls-qr",
    type: "qr",
    field: "badgeNo",
    x: 55,
    y: 265,
    width: 90,
    height: 90,
    backgroundColor: "#ffffff",
    borderRadius: 6,
    zIndex: 3
  },
  {
    id: "ls-garuda",
    type: "emblem",
    field: "static",
    content: "garuda",
    x: 225,
    y: 22,
    width: 60,
    height: 54,
    zIndex: 2
  },
  {
    id: "ls-hdr",
    type: "text",
    field: "static",
    content: "บัตรประจำตัวเจ้าหน้าที่สังกัด",
    x: 295,
    y: 22,
    width: 280,
    height: 22,
    fontSize: 12,
    color: "#64748b",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "ls-dept",
    type: "text",
    field: "department",
    x: 295,
    y: 46,
    width: 280,
    height: 26,
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "ls-line",
    type: "line",
    field: "static",
    x: 225,
    y: 86,
    width: 350,
    height: 2,
    backgroundColor: "#e2e8f0",
    zIndex: 1
  },
  {
    id: "ls-name",
    type: "text",
    field: "fullName",
    x: 225,
    y: 104,
    width: 350,
    height: 38,
    fontSize: 18,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "ls-pos",
    type: "text",
    field: "position",
    x: 225,
    y: 146,
    width: 350,
    height: 26,
    fontSize: 13,
    color: "#3b82f6",
    dynamicText: true,
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "ls-rank",
    type: "ribbon",
    field: "rank",
    x: 225,
    y: 184,
    width: 215,
    height: 30,
    fontSize: 10.5,
    color: "#ffffff",
    backgroundColor: "#3b82f6",
    dynamicBg: true,
    fontWeight: "bold",
    textAlign: "center",
    borderRadius: 14,
    zIndex: 2
  },
  {
    id: "ls-bld",
    type: "text",
    field: "static",
    content: "หมู่โลหิต: O (Rh+)",
    x: 455,
    y: 188,
    width: 120,
    height: 22,
    fontSize: 11,
    color: "#dc2626",
    fontWeight: "bold",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "ls-barcode",
    type: "barcode",
    field: "badgeNo",
    x: 225,
    y: 245,
    width: 340,
    height: 70,
    zIndex: 2
  },
  {
    id: "ls-foot",
    type: "text",
    field: "static",
    content: "EXECUTIVE IDENTIFICATION CARD",
    x: 225,
    y: 340,
    width: 350,
    height: 20,
    fontSize: 9,
    color: "#94a3b8",
    letterSpacing: 1,
    textAlign: "left",
    zIndex: 2
  }
];

export const TEMPLATE_BACK_STANDARD: CanvasElement[] = [
  {
    id: "b-bg",
    type: "rect",
    field: "static",
    x: 0,
    y: 0,
    width: 380,
    height: 600,
    backgroundColor: "#ffffff",
    zIndex: 0
  },
  {
    id: "b-title",
    type: "text",
    field: "static",
    content: "ข้อกำหนดและระเบียบการใช้บัตร",
    x: 0,
    y: 35,
    width: 380,
    height: 42,
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "b-line1",
    type: "line",
    field: "static",
    x: 40,
    y: 88,
    width: 300,
    height: 2,
    backgroundColor: "#cbd5e1",
    zIndex: 1
  },
  {
    id: "b-p1",
    type: "text",
    field: "static",
    content: "1. บัตรนี้เป็นทรัพย์สินของทางราชการ ห้ามโอนหรือมอบให้ผู้อื่นนำไปใช้โดยเด็ดขาด",
    x: 30,
    y: 112,
    width: 320,
    height: 55,
    fontSize: 9.5,
    color: "#475569",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "b-p2",
    type: "text",
    field: "static",
    content: "2. ต้องแสดงบัตรนี้ทุกครั้งเมื่อผ่านเข้า-ออกพื้นที่ควบคุม และขณะปฏิบัติหน้าที่",
    x: 30,
    y: 175,
    width: 320,
    height: 55,
    fontSize: 9.5,
    color: "#475569",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "b-p3",
    type: "text",
    field: "static",
    content: "3. กรณีบัตรสูญหายหรือชำรุด ให้รีบแจ้งหน่วยงานต้นสังกัดเพื่อดำเนินการออกบัตรใหม่ทันที",
    x: 30,
    y: 238,
    width: 320,
    height: 55,
    fontSize: 9.5,
    color: "#475569",
    textAlign: "left",
    zIndex: 2
  },
  {
    id: "b-qr",
    type: "qr",
    field: "badgeNo",
    x: 130,
    y: 325,
    width: 120,
    height: 120,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 8,
    zIndex: 3
  },
  {
    id: "b-qr-lbl",
    type: "text",
    field: "static",
    content: "สแกนเพื่อตรวจสอบความถูกต้องดิจิทัล",
    x: 0,
    y: 458,
    width: 380,
    height: 28,
    fontSize: 9,
    color: "#64748b",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "b-line2",
    type: "line",
    field: "static",
    x: 40,
    y: 500,
    width: 300,
    height: 2,
    backgroundColor: "#cbd5e1",
    zIndex: 1
  },
  {
    id: "b-org",
    type: "text",
    field: "department",
    x: 0,
    y: 520,
    width: 380,
    height: 30,
    fontSize: 10,
    color: "#0f172a",
    fontWeight: "bold",
    textAlign: "center",
    zIndex: 2
  },
  {
    id: "b-addr",
    type: "text",
    field: "static",
    content: "กรุณาส่งคืนตามที่อยู่หน่วยงานต้นสังกัด",
    x: 0,
    y: 552,
    width: 380,
    height: 24,
    fontSize: 8.5,
    color: "#64748b",
    textAlign: "center",
    zIndex: 2
  }
];
