import * as fs from 'fs';
import * as path from 'path';

const MODULES_DIR = path.resolve(__dirname, '../src/modules');
const EXTENSIONS_DIR = path.resolve(__dirname, '../extensions');
const EXCLUDE_CORE_DIRS = ['core'];

interface ModuleEntry {
  mod: string;
  importPath: string; // e.g. '@/modules/e-form'
}

function scanDirectory(dir: string, excludeDirs: string[] = []): ModuleEntry[] {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true })
    .filter(e => e.isDirectory() && !excludeDirs.includes(e.name))
    .map(e => ({
      mod: e.name,
      importPath: `@/modules/${e.name}`,
    }));
}

function scanModules() {
  // Core modules (src/modules/) — excludes 'core' itself
  const coreModules = scanDirectory(MODULES_DIR, EXCLUDE_CORE_DIRS);
  // Extension modules (extensions/)
  const extensionModules = scanDirectory(EXTENSIONS_DIR);

  const allModules = [...coreModules, ...extensionModules];

  const manifests: { mod: string; importPath: string; originalName: string; aliasName: string }[] = [];
  const views: { mod: string; importPath: string; originalName: string; aliasName: string }[] = [];

  for (const { mod, importPath } of allModules) {
    const safeModName = mod.replace(/[^a-zA-Z0-9]/g, '_');

    // Resolve the actual filesystem path for reading
    const isCoreModule = coreModules.some(m => m.mod === mod);
    const fsBase = isCoreModule
      ? path.join(MODULES_DIR, mod)
      : path.join(EXTENSIONS_DIR, mod);

    const manifestPath = path.join(fsBase, 'manifest.ts');
    if (fs.existsSync(manifestPath)) {
      const content = fs.readFileSync(manifestPath, 'utf-8');
      const regex = /export\s+const\s+([A-Za-z0-9_]+)(?:\s*:\s*ModuleManifest)?\s*=/g;
      let match;
      while ((match = regex.exec(content)) !== null) {
        manifests.push({
          mod,
          importPath,
          originalName: match[1],
          aliasName: `${safeModName}_${match[1]}`,
        });
      }
    }

    const indexPath = path.join(fsBase, 'index.ts');
    if (fs.existsSync(indexPath)) {
      const content = fs.readFileSync(indexPath, 'utf-8');
      const regex = /export\s+const\s+([A-Za-z0-9_]+)(?:\s*:\s*ModuleDefinition)?\s*=/g;
      let match;
      while ((match = regex.exec(content)) !== null) {
        views.push({
          mod,
          importPath,
          originalName: match[1],
          aliasName: `${safeModName}_${match[1]}`,
        });
      }
    }
  }

  return { manifests, views };
}

function generateFiles() {
  const { manifests, views } = scanModules();

  let manifestsContent = `// THIS FILE IS AUTO-GENERATED BY npm run module:sync\n// DO NOT EDIT DIRECTLY\n\n`;
  for (const item of manifests) {
    manifestsContent += `import { ${item.originalName} as ${item.aliasName} } from '${item.importPath}/manifest';\n`;
  }
  manifestsContent += `\nexport const GENERATED_MANIFESTS = [\n  ${manifests.map(m => m.aliasName).join(',\n  ')}\n];\n`;
  manifestsContent += `\nexport const GENERATED_MANIFEST_EXPORTS = {\n  ${manifests.map(m => `${m.originalName}: ${m.aliasName}`).join(',\n  ')}\n};\n`;

  fs.writeFileSync(path.join(MODULES_DIR, 'core', 'generated-manifests.ts'), manifestsContent);
  console.log('✅ Generated src/modules/core/generated-manifests.ts');

  let viewsContent = `// THIS FILE IS AUTO-GENERATED BY npm run module:sync\n// DO NOT EDIT DIRECTLY\n\n`;
  for (const item of views) {
    viewsContent += `import { ${item.originalName} as ${item.aliasName} } from '${item.importPath}';\n`;
  }
  viewsContent += `\nexport const GENERATED_MODULE_ARRAY = [\n  ${views.map(v => v.aliasName).join(',\n  ')}\n];\n`;
  viewsContent += `\nexport const GENERATED_MODULE_EXPORTS = {\n  ${views.map(v => `${v.originalName}: ${v.aliasName}`).join(',\n  ')}\n};\n`;

  fs.writeFileSync(path.join(MODULES_DIR, 'core', 'generated-views.ts'), viewsContent);
  console.log('✅ Generated src/modules/core/generated-views.ts');
}

generateFiles();
