// THIS FILE IS AUTO-GENERATED BY npm run module:sync
// DO NOT EDIT DIRECTLY

import { AuthManifest as auth_AuthManifest } from '@/modules/auth/manifest';
import { DashboardManifest as dashboard_DashboardManifest } from '@/modules/dashboard/manifest';
import { InstallManifest as install_InstallManifest } from '@/modules/install/manifest';
import { RolesManifest as roles_RolesManifest } from '@/modules/roles/manifest';
import { SiteManifest as site_SiteManifest } from '@/modules/site/manifest';
import { SiteContentManifest as site_SiteContentManifest } from '@/modules/site/manifest';
import { TestSlipManifest as test_slip_TestSlipManifest } from '@/modules/test-slip/manifest';
import { themeManifest as theme_themeManifest } from '@/modules/theme/manifest';
import { UsersManifest as users_UsersManifest } from '@/modules/users/manifest';
import { PersonnelManifest as users_PersonnelManifest } from '@/modules/users/manifest';
import { ApiDocsManifest as api_docs_ApiDocsManifest } from '@/modules/api-docs/manifest';
import { backupManifest as backup_backupManifest } from '@/modules/backup/manifest';
import { BadgesManifest as badges_BadgesManifest } from '@/modules/badges/manifest';
import { CalendarManifest as calendar_CalendarManifest } from '@/modules/calendar/manifest';
import { ContactsManifest as contacts_ContactsManifest } from '@/modules/contacts/manifest';
import { documentTemplatesManifest as document_templates_documentTemplatesManifest } from '@/modules/document-templates/manifest';
import { manifest as document_templates_manifest } from '@/modules/document-templates/manifest';
import { EFormManifest as e_form_EFormManifest } from '@/modules/e-form/manifest';
import { InspectorManifest as inspector_InspectorManifest } from '@/modules/inspector/manifest';
import { SystemInspectorManifest as inspector_SystemInspectorManifest } from '@/modules/inspector/manifest';
import { NewsManifest as news_NewsManifest } from '@/modules/news/manifest';
import { PrintManifest as print_PrintManifest } from '@/modules/print/manifest';
import { UploadManifest as upload_UploadManifest } from '@/modules/upload/manifest';

export const GENERATED_MANIFESTS = [
  auth_AuthManifest,
  dashboard_DashboardManifest,
  install_InstallManifest,
  roles_RolesManifest,
  site_SiteManifest,
  site_SiteContentManifest,
  test_slip_TestSlipManifest,
  theme_themeManifest,
  users_UsersManifest,
  users_PersonnelManifest,
  api_docs_ApiDocsManifest,
  backup_backupManifest,
  badges_BadgesManifest,
  calendar_CalendarManifest,
  contacts_ContactsManifest,
  document_templates_documentTemplatesManifest,
  document_templates_manifest,
  e_form_EFormManifest,
  inspector_InspectorManifest,
  inspector_SystemInspectorManifest,
  news_NewsManifest,
  print_PrintManifest,
  upload_UploadManifest
];

export const GENERATED_MANIFEST_EXPORTS = {
  AuthManifest: auth_AuthManifest,
  DashboardManifest: dashboard_DashboardManifest,
  InstallManifest: install_InstallManifest,
  RolesManifest: roles_RolesManifest,
  SiteManifest: site_SiteManifest,
  SiteContentManifest: site_SiteContentManifest,
  TestSlipManifest: test_slip_TestSlipManifest,
  themeManifest: theme_themeManifest,
  UsersManifest: users_UsersManifest,
  PersonnelManifest: users_PersonnelManifest,
  ApiDocsManifest: api_docs_ApiDocsManifest,
  backupManifest: backup_backupManifest,
  BadgesManifest: badges_BadgesManifest,
  CalendarManifest: calendar_CalendarManifest,
  ContactsManifest: contacts_ContactsManifest,
  documentTemplatesManifest: document_templates_documentTemplatesManifest,
  manifest: document_templates_manifest,
  EFormManifest: e_form_EFormManifest,
  InspectorManifest: inspector_InspectorManifest,
  SystemInspectorManifest: inspector_SystemInspectorManifest,
  NewsManifest: news_NewsManifest,
  PrintManifest: print_PrintManifest,
  UploadManifest: upload_UploadManifest
};
