// THIS FILE IS AUTO-GENERATED BY npm run module:sync
// DO NOT EDIT DIRECTLY

import { ApiDocsModule as api_docs_ApiDocsModule } from '@/modules/api-docs';
import { AuthModule as auth_AuthModule } from '@/modules/auth';
import { BackupModule as backup_BackupModule } from '@/modules/backup';
import { BadgesModule as badges_BadgesModule } from '@/modules/badges';
import { CalendarModule as calendar_CalendarModule } from '@/modules/calendar';
import { ContactsModule as contacts_ContactsModule } from '@/modules/contacts';
import { DashboardModule as dashboard_DashboardModule } from '@/modules/dashboard';
import { documentTemplatesModule as document_templates_documentTemplatesModule } from '@/modules/document-templates';
import { InspectorModule as inspector_InspectorModule } from '@/modules/inspector';
import { SystemInspectorModule as inspector_SystemInspectorModule } from '@/modules/inspector';
import { InstallModule as install_InstallModule } from '@/modules/install';
import { LeavesModule as leaves_LeavesModule } from '@/modules/leaves';
import { ModuleManagerModule as module_manager_ModuleManagerModule } from '@/modules/module-manager';
import { NewsModule as news_NewsModule } from '@/modules/news';
import { PrintModule as print_PrintModule } from '@/modules/print';
import { RolesModule as roles_RolesModule } from '@/modules/roles';
import { SiteModule as site_SiteModule } from '@/modules/site';
import { SiteContentModule as site_SiteContentModule } from '@/modules/site';
import { SiteContentView as site_SiteContentView } from '@/modules/site';
import { TestSlipModule as test_slip_TestSlipModule } from '@/modules/test-slip';
import { ThemeModule as theme_ThemeModule } from '@/modules/theme';
import { UploadModule as upload_UploadModule } from '@/modules/upload';
import { UsersModule as users_UsersModule } from '@/modules/users';
import { PersonnelModule as users_PersonnelModule } from '@/modules/users';

export const GENERATED_MODULE_ARRAY = [
  api_docs_ApiDocsModule,
  auth_AuthModule,
  backup_BackupModule,
  badges_BadgesModule,
  calendar_CalendarModule,
  contacts_ContactsModule,
  dashboard_DashboardModule,
  document_templates_documentTemplatesModule,
  inspector_InspectorModule,
  inspector_SystemInspectorModule,
  install_InstallModule,
  leaves_LeavesModule,
  module_manager_ModuleManagerModule,
  news_NewsModule,
  print_PrintModule,
  roles_RolesModule,
  site_SiteModule,
  site_SiteContentModule,
  site_SiteContentView,
  test_slip_TestSlipModule,
  theme_ThemeModule,
  upload_UploadModule,
  users_UsersModule,
  users_PersonnelModule
];

export const GENERATED_MODULE_EXPORTS = {
  ApiDocsModule: api_docs_ApiDocsModule,
  AuthModule: auth_AuthModule,
  BackupModule: backup_BackupModule,
  BadgesModule: badges_BadgesModule,
  CalendarModule: calendar_CalendarModule,
  ContactsModule: contacts_ContactsModule,
  DashboardModule: dashboard_DashboardModule,
  documentTemplatesModule: document_templates_documentTemplatesModule,
  InspectorModule: inspector_InspectorModule,
  SystemInspectorModule: inspector_SystemInspectorModule,
  InstallModule: install_InstallModule,
  LeavesModule: leaves_LeavesModule,
  ModuleManagerModule: module_manager_ModuleManagerModule,
  NewsModule: news_NewsModule,
  PrintModule: print_PrintModule,
  RolesModule: roles_RolesModule,
  SiteModule: site_SiteModule,
  SiteContentModule: site_SiteContentModule,
  SiteContentView: site_SiteContentView,
  TestSlipModule: test_slip_TestSlipModule,
  ThemeModule: theme_ThemeModule,
  UploadModule: upload_UploadModule,
  UsersModule: users_UsersModule,
  PersonnelModule: users_PersonnelModule
};
